name = "Lean-Learning"
version = "0.0.1"
extra_files = "extras"
intro = "src/intro.lean"

[[worlds]]
name = "Intro World"
id = 1
levels = [
	"src/introWorld/first.lean",
]

[[worlds]]
name = "Tactic World"
id = 2
parents = [1]
levels = [
  "src/tacticworld/refl.lean",
	"src/tacticworld/exact.lean",
  "src/tacticworld/simp.lean",
  "src/tacticworld/intro.lean",
]